### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by sr66139p** [itprojects/MasVisGtk#1]
I noticed that the Flatpak is mentioned in the README, but it isn't verified on Flathub. Would you consider verifying it to let people know it's an official package? Distros Like Linux Mint and elementaryOS hide or provide warnings on unverified flatpaks. Here's a link to the documentation on how to verify on Flathub https://docs.flathub.org/docs/for-app-authors/verification.

**Comment by itprojects** [comment]
No. Please respect that choice.
